"""add validation reports, event outbox

Revision ID: 41abd7807d9e
Revises: abc12345ef78901
Create Date: 2026-06-24 17:52:39.095952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41abd7807d9e'
down_revision: Union[str, Sequence[str], None] = 'abc12345ef78901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_outbox_aggregate_id'), 'event_outbox', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_event_outbox_event_type'), 'event_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_outbox_id'), 'event_outbox', ['id'], unique=False)
    op.create_index(op.f('ix_event_outbox_published'), 'event_outbox', ['published'], unique=False)
    op.create_table('crawl_validation_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_run_id', sa.Integer(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('avg_content_length', sa.Float(), nullable=True),
    sa.Column('fields_missing_rate', sa.Float(), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_validation_reports_crawl_run_id'), 'crawl_validation_reports', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_crawl_validation_reports_id'), 'crawl_validation_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_validation_reports_id'), table_name='crawl_validation_reports')
    op.drop_index(op.f('ix_crawl_validation_reports_crawl_run_id'), table_name='crawl_validation_reports')
    op.drop_table('crawl_validation_reports')
    op.drop_index(op.f('ix_event_outbox_published'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_id'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_event_type'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_aggregate_id'), table_name='event_outbox')
    op.drop_table('event_outbox')
    # ### end Alembic commands ###
